version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-ecommerce
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.user
    container_name: user-service
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=db-user
      - SPRING_DATASOURCE_PASSWORD=db-password

  product-service:
    build:
      context: .
      dockerfile: Dockerfile.product
    container_name: product-service
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=db-user
      - SPRING_DATASOURCE_PASSWORD=db-password

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service