apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-ecommerce.fullname" . }}-user
  namespace: {{ .Release.Namespace | quote }}   
  labels:
    app: {{ include "simple-ecommerce.fullname" . }}-user
    chart: {{ include "simple-ecommerce.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.user.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-ecommerce.fullname" . }}-user
  template:
    metadata:
      labels:
        app: {{ include "simple-ecommerce.fullname" . }}-user
    spec:
      containers:
      - name: {{ include "simple-ecommerce.fullname" . }}-user
        image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
        imagePullPolicy: {{ .Values.user.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.user.ports.containerPort }}
        resources:
          requests:
            memory: {{ .Values.user.resources.requests.memory }}
            cpu: {{ .Values.user.resources.requests.cpu }}
          limits:
            memory: {{ .Values.user.resources.limits.memory }}
            cpu: {{ .Values.user.resources.limits.cpu }}
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.appConfigName }}
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.appConfigName }}
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.appConfigName }}
              key: SPRING_DATASOURCE_PASSWORD
