apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{include "simple-ecommerce.fullname" . }}-product
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{include "simple-ecommerce.fullname" . }}-product
    chart: {{ include "simple-ecommerce.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
    replicas: {{ .Values.product.replicaCount | quote }}
    selector:
        matchLabels:
        app: {{include "simple-ecommerce.fullname" . }}-product
    template:
        metadata:
        labels:
            app: {{include "simple-ecommerce.fullname" . }}-product
        spec:
        containers:
            - name: {{include "simple-ecommerce.fullname" . }}-product
              image: {{ .Values.product.image.repository | quote }}:{{ .Values.product.image.tag | quote }}
              imagePullPolicy: {{ .Values.product.image.pullPolicy | quote }}
              ports:
                - containerPort: {{ .Values.product.containerPort | quote }}
              resources:
                requests:
                memory: {{ .Values.product.resources.requests.memory | quote }}
                cpu: {{ .Values.product.resources.requests.cpu | quote }}
                limits:
                memory: {{ .Values.product.resources.limits.memory | quote }}
                cpu: {{ .Values.product.resources.limits.cpu | quote }}
              env:
                - name: SPRING_DATASOURCE_URL
                  valueFrom:
                    secretKeyRef:
                    name: {{ .Values.secrets.appConfigName | quote }}
                    key: SPRING_DATASOURCE_URL
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                    name: {{ .Values.secrets.appConfigName | quote }}
                    key: SPRING_DATASOURCE_USERNAME
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                    name: {{ .Values.secrets.appConfigName | quote }}
                    key: SPRING_DATASOURCE_PASSWORD