apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-ecommerce.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "simple-ecommerce.fullname" . }}-frontend
    chart: {{ include "simple-ecommerce.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simple-ecommerce.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "simple-ecommerce.fullname" . }}-frontend
    spec:
      containers:
        - name: {{ include "simple-ecommerce.fullname" . }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          resources:
            requests:
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
