{{- if .Values.secrets.appConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appConfigName | quote }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.appConfig }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}

{{- if .Values.secrets.dbSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.dbSecret }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}