apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.product.service.name | quote }}
    namespace: {{ .Release.Namespace | quote }}
    labels:
        app: {{ Values.product.service.name | quote }}
        chart: {{ include "simple-ecommerce.chart" . }}
        release: {{ .Release.Name | quote }}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: {{ .Values.product.service.port | quote }}
          targetPort: {{ .Values.product.containerPort | quote }}
    selector:
        app: {{ include "simple-ecommerce.fullname" . }}-product