apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user.service.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.user.service.name | quote }}
    chart: {{ include "simple-ecommerce.chart" . }}
    release: {{ .Release.Name | quote }}
spec:
    type: ClusterIP
    ports:
        - name: http
          port: {{ .Values.user.service.port | quote }}
          targetPort: {{ .Values.user.containerPort | quote }}
    selector:
        app: {{ include "simple-ecommerce.fullname" . }}-user