apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
        app: {{ .Values.frontend.service.name | quote }}
        chart: {{ include "simple-ecommerce.chart" . }}
        release: {{ .Release.Name | quote }}
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: {{ .Values.frontend.service.port | quote }}
          targetPort: {{ .Values.frontend.containerPort | quote }}
    selector:
        app: {{ include "simple-ecommerce.fullname" . }}-frontend