apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: nfs-sc
