# Build from root directory
FROM maven:3.8.5-openjdk-17-slim AS builder
WORKDIR /app
COPY pom.xml .
COPY src/ ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /app/target/simple-ecommerce-0.0.1-SNAPSHOT-product.jar app.jar
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]