#Build from root directory
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY frontend/ /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/nginx.conf 
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]