apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: postgres-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: storage-disk
    fsType: ext4
